### ISSUE TITLE
Biometric authentication using Java 

### ISSUE THREAD

**Issue by AdarshBP** [saucelabs-training/demo-java#42]
Hi team , could you please guide me on implementing biometric authentication using Java code.l, I went through your repo but found the code in java script , could you please help me using Java

**Comment by eyaly** [comment]
Hi @AdarshBP - Thanks for the feedback. For now, we have an example in JS, as you mention. Hopefully, we will also have a Java code example next week.

**Comment by AdarshBP** [comment]
Thk you @eyaly ... Is biometric authentication is restricted to app.saucelabs.com or can we do in legacy Real device in app.testobjects.com

**Comment by eyaly** [comment]
Hi @AdarshBP. Biometric authentication can be done also on legacy Real devices. The support for Touch ID is done by Appium. Please read:
http://appium.io/docs/en/commands/device/simulator/touch-id/

For iOS you need to add the capability:
capabilities.setCapability("allowTouchIdEnroll", true);

And when you need to use touch id:
driver.performTouchID(true);

Hope it helps,
Eyal
